### ISSUE TITLE
auto crafting Stuck

### ISSUE THREAD

**Issue by GamerAffair** [Ellpeck/PrettyPipes#88] opened 2021-06-19 00:13 UTC
So im trying to set up an auto crafting system using pretty pipes and the Rats mod, it worked well, at first.

Now it gets stuck on "Awaiting" and it never sends any items to be crafted.

odd thing is, that it works fine on my creative world. And if I make a small pipe network to the side it works fine.

is there a way to fix this or to better set up my pipes to allow the logic to work more efficiently?

many thanks!

**Comment by Ellpeck** [comment] 2021-06-19 00:16
Have you tried restarting the server you're playing on (in case it's not singleplayer!) or breaking and replacing the pipes that have the crafting modules in them?

It would be good if you could create a video or some screenshots (or just a description) that explains what happens to the items that are sent off to craft with. Are they actually being sent off? Are they getting stuck somewhere? Are they maybe dropping out of a pipe somewhere for some reason?

**Comment by GamerAffair** [comment] 2021-06-19 00:21
I've completely reworked my pip system just about 30 mins ago still didn't work but I can have the server restarted one moment.

alos i can confirm that the items never leave the chest when auto crafting is initiated.

**Comment by GamerAffair** [comment] 2021-06-19 00:27
Restarting the server did fix it thanks!

**Comment by GamerAffair** [comment] 2021-06-19 00:27
it was odd tho because it would work on the server if I made a small side pipe network even before the restart

**Comment by Ellpeck** [comment] 2021-06-19 00:28
If restarting fixes it, then this is a duplicate of #86!

**Closed by Ellpeck** 2021-06-19 00:28 UTC
