### ISSUE TITLE
[1.16.3] Server hard lock on request of 500 hemp.

### ISSUE THREAD

**Issue by ProsperCraft** [Ellpeck/PrettyPipes#36] opened 2020-10-07 04:02 UTC
A player on our dedicated server testing TownCraft TWO requested 500 hemp and it never produced it, it locked the server hard, we waited about 40 minutes before killing the server, it never returned until we killed the process and restarted it.

106 meg debug log-
[debug.zip](https://github.com/Ellpeck/PrettyPipes/files/5338183/debug.zip)
Latest log-
[latest.log](https://github.com/Ellpeck/PrettyPipes/files/5338184/latest.log)
Warmroast of the server while it is locked up-
[prettypipes-warmroast.zip](https://github.com/Ellpeck/PrettyPipes/files/5338186/prettypipes-warmroast.zip)
Screenshot of the warmroast-
![image](https://user-images.githubusercontent.com/4427684/95285907-230d1380-081f-11eb-83bf-5b5859a69d0a.png)

PrettyPipes-1.6.0
forge-1.16.3-34.1.9.jar

**Comment by Ellpeck** [comment] 2020-10-07 04:18
What do you mean by "it never produced it"?

**Comment by ProsperCraft** [comment] 2020-10-07 04:37
the request was made, and the server hard locked.

**Comment by Ellpeck** [comment] 2020-10-07 04:42
Are you able to reproduce this issue?

**Comment by ProsperCraft** [comment] 2020-10-07 05:15
no, he is not able to reproduce, he suspects it might have something to do with a bug we are seeing on the server where some items don't stack...sticks, crops, ect...we have not been able to pin that one down yet, you throw them on the ground, and they merge, looking at them with F3+H shows identical nbt tags.

**Comment by Ellpeck** [comment] 2020-10-07 05:17
I'm not really sure how I would go about fixing this, since the logs don't really tell me that much. Since the server was pretty laggy to begin with (lots of skipped ticks), I assume it's a combination of some sort of broken mod interaction and lag. 

I'm closing this issue for now, but if the same thing (or something similar) happens again, you can just re-open it. Good luck!

**Closed by Ellpeck** 2020-10-07 05:17 UTC
