### ISSUE TITLE
Items being miscounted in the inventory

### ISSUE THREAD

**Issue by Chassx2** [Ellpeck/PrettyPipes#155] opened 2022-10-01 09:28 UTC
Items are not being counted correctly in the standard minecraft chests.

![2022-10-01_05 27 19](https://user-images.githubusercontent.com/56740526/193402777-3f61f5a7-be80-4026-a9c2-f00313c3faa8.png)

**Comment by Ellpeck** [comment] 2022-10-01 09:39
Duplicate of #152. Please check open issues before reporting your own.

**Closed by Ellpeck** 2022-10-01 09:39 UTC
