### ISSUE TITLE
BUG TO REQUEST ITEMS 

### ISSUE THREAD

**Issue by Nahueamado** [Ellpeck/PrettyPipes#146] opened 2022-08-25 05:32 UTC
when I ask for several items at the same time, (example 20, sometimes I get all 20, or sometimes only half)

I had 54 gold, I asked for the 54 and I received 27 and the others are not there

**Comment by Ellpeck** [comment] 2022-08-30 20:40
What version of Pretty Pipes are you on?

If you're on an older version of Minecraft, connecting a single double chest to the pipe network twice will cause the issue you're describing. If that is the case for your network, this issue cannot reasonably be fixed unfortunately, as it is an incompatibility with how Minecraft's default code handles double chests.

**Comment by Ellpeck** [comment] 2022-09-13 18:57
Duplicate of #152

**Closed by Ellpeck** 2022-09-13 18:57 UTC
