### ISSUE TITLE
Duplication glitch

### ISSUE THREAD

**Issue by James-Sergeant** [Ellpeck/PrettyPipes#112] opened 2022-01-04 19:27 UTC
Enigmatic 6 developer build mod version:- 1.9.5 

Block:- Crafting Terminal

Steps to reproduce:
1) Place a recipe in and request request items,
2) Ask another player to also enter the terminal.
3) Both players take out the item at around the same time(Seems to be quite lenient)
4) Profit, you have two of the items for free!

**Comment by Ellpeck** [comment] 2022-01-04 19:30
This issue is already fixed in the 1.18 version of the mod. The 1.16 version is not supported anymore, unfortunately.

**Closed by Ellpeck** 2022-01-04 19:30 UTC

**Comment by NillerMedDild** [comment] 2022-01-24 12:51
This is a pretty bad dupe bug tbf, could you please make an exception and backport the fix?

**Comment by Ellpeck** [comment] 2022-01-24 13:21
For anyone who is still in 1.16, please try to reproduce this issue using [this build](https://ci.ellpeck.de/job/PrettyPipes/job/1.16/3/artifact/build/libs/PrettyPipes-1.9.5.3.jar). Thanks!

**Comment by AWrongUsername** [comment] 2022-01-24 21:47
Hello,
The provided build sadly still has this issue. 
PrettyPipes-1.9.5.3 with Forge forge-1.16.5-36.2.23.

**Comment by Ellpeck** [comment] 2022-01-24 22:10
What aboooout [this build](https://ci.ellpeck.de/job/PrettyPipes/job/1.16/5/artifact/build/libs/PrettyPipes-1.9.5.5.jar)?

**Comment by AWrongUsername** [comment] 2022-01-24 22:15
This build has fixed the issue. Thank you so much!

**Comment by Ellpeck** [comment] 2022-01-24 22:16
Yay! I shall release this version soon.

**Comment by MuteTiefling** [comment] 2022-01-24 22:51
Thanks a bunch Ell <3
