### ISSUE TITLE
Clear modules to default state so they can stack again.

### ISSUE THREAD

**Issue by osirisgothra** [Ellpeck/PrettyPipes#183] opened 2023-03-23 17:33 UTC
Currently, to clear the module, I have to put it into the pipe, clear it "manually" and take it back out, unless I want to do that with each pipe before I tear it down, but that is not always favorable either especially with large or automated rebuilds.

Some of my setups can use as many as 30 pipes. If I decide to tear it down and want to store the modules for later use, it is a major pain. With 1-3 modules a piece that's going to be up to 90 times to repeat the process. If it takes me about 6 seconds per module, then we are talking almost 10 minutes.... That is _if_ I am able to keep that pace. Realistically it would be more like 13-15 minutes. 

In contrast, throwing them in the crafting grid to clear them takes seconds and can even be done automatically. I was kind of surprised that this wasn't a feature.  If not that, then holding the module and sneak-click or something to clear them.

What I've resorted to is just trashing them and making new ones.

**Comment by Ellpeck** [comment] 2023-07-25 13:23
Duplicate of #79

**Closed by Ellpeck** 2023-07-25 13:23 UTC
